### PR TITLE
Done issue #4

### LINKED ISSUE #4: Add GitHub Action pipeline to upload package to pypi

### LINKED ISSUE #7: Ensure package is compatible with Python 3.8

### PR DESCRIPTION
**Pull request by shivamsn97**
Added workflow to publish to PyPi.
Make sure to add your secrets.

PYPI_USERNAME = your pypi username
PYPI_PASSWORD = your pypi password

### CODE REVIEW

**Comment by conruggles** [comment]
@wevnasc Hey I hope you hadn't already started work on this, but this looks good to me. I'm going to hold off on merging until we have some coordination here, but I'm good with using this PR.

**Comment by conruggles** [comment]
Okay going back on this, I think in order for this to build with 3.8 we need to ensure the code is compatible with 3.8 (currently works with at least 3.5). I will create a new issue for that if you'd like to take it @shivamsn97  #7

**Comment by shivamsn97** [comment]
No need for issue #7. You can build with 3.5 too, by just changing that version in workflow file. I will push a commit for that.

**Comment by conruggles** [comment]
@shivamsn97 okay sounds good, please do so

**Comment by shivamsn97** [comment]
Done

**Comment by conruggles** [comment]
I'd still like to wait to merge, but like I said it all looks good. Thank you for adding this.

**Comment by shivamsn97** [comment]
I guess there is some isse while using python3.5. Check the following screenshot.
image

setup.py had worked very well when used on 3.8, see ss:
image

**Comment by shivamsn97** [comment]
Would you like to revert the last commit and make it use 3.8 only? The code is already compatible with 3.8.

**Comment by conruggles** [comment]
Huh interesting, yeah let's just use 3.8 since it clearly works fine. Thanks for your patience on this

**Comment by shivamsn97** [comment]
Okay I am reverting the last commit.

**Comment by conruggles** [comment]
Awesome, I'm going to merge.

**Pull request merged**
